# Generated by Django 4.2.4 on 2023-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=30)),
                ('huella', models.IntegerField()),
                ('informacion', models.CharField(max_length=400)),
            ],
        ),
    ]
