# Generated by Django 4.2.4 on 2023-10-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usuarios_registroco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivos',
            old_name='huella',
            new_name='Huella',
        ),
        migrations.RemoveField(
            model_name='objetivos',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='objetivos',
            name='informacion',
        ),
        migrations.AddField(
            model_name='objetivos',
            name='Acumulable',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetivos',
            name='Categoria',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetivos',
            name='Accion',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
