# Generated by Django 4.2.4 on 2023-10-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_huella_objetivos_huella_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accion', models.CharField(max_length=50)),
                ('Categoria', models.CharField(max_length=50)),
                ('Acumulable', models.BooleanField()),
                ('Huella', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='objetivos',
        ),
    ]
