# Generated by Django 4.2.4 on 2023-10-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='Preferencias',
            field=models.CharField(default='t,'),
        ),
    ]
