# Generated by Django 4.2.4 on 2023-10-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_configuracion_preferencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroco',
            name='Repositorio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
