# Generated by Django 4.2.4 on 2023-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_configuracion_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='Deuda',
            field=models.DecimalField(decimal_places=2, default=4400.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registroco',
            name='Repositorio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
